[project]
name = "support-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "xteam jack", email = "xteam.jack@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
support-agent = "support_agent:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
